### PR TITLE
Fix/slot fixes

### PR DESCRIPTION
**Pull request by mauerk**
Fixes issue (if applicable) #

## Proposed Changes

  - deprecated slots: research_data_file, process_data_file, individual_supporting_file, experiment_method_supporting_file, individual_supporting_file
  - renamed "is_pseudofile" slot to "included_in_submission"
  - changed "required" flags in Submission class to "true"
  
## Checks
  - [ ] Builds locally

### CODE REVIEW

**Review by lkuchenb — COMMENTED** [review]
Can we move the `included_in_submission` slot to the base File class to make it available to all classes?

**Comment by mauerk** [comment]
> Can we move the `included_in_submission` slot to the base File class to make it available to all classes?

@lkuchenb The "included_in_submission" slot is only needed in the ResearchDataFile class in case someone wants to submit processed files without the raw files. To make the linkage to Experiment and Sample/Individual work in this case, they have to register pseudofiles. For all other files that are registered in the respective spreadsheets we expect that they are part of the submission. We can change the slot description to be more specific?

**Comment by mauerk** [comment]
Thanks for the clarification, makes sense to solve that on a policy level 👍 I'll change the slot position like you asked.

**Review by lkuchenb — APPROVED** [review]
LGTM, I think descriptions need fixes, but that's not blocking I'd say.

**Review by lkuchenb — APPROVED** [review]

**Pull request merged**
